import React from 'react';
import { ComponentMeta } from '@storybook/react';
declare const _default: ComponentMeta<(props: React.PropsWithChildren<import("../interfaces/CommonInterface").ButtonProps>) => JSX.Element>;
export default _default;
export declare const Primary: any;
export declare const Contained: any;
export declare const Outline: any;
export declare const Upload: any;
export declare const startIcon: any;
export declare const endIcon: any;
